### ISSUE TITLE
Item 21 Emails 404

### ISSUE THREAD

**Issue by spbriggs** [ozlerhakan/mongodb-json-files#2]
Item 21 on your list "Email" is now 404ing. I think this might be the correct link : https://www.cs.cmu.edu/~enron/enron_mail_20150507.tar.gz

I'm guessing though that this item is a duplicate of the "Enron" item (number 2 on your list)

**Comment by ozlerhakan** [comment]
Thank you @spbriggs , I'll update the link and I need to observe for the second case
