### ISSUE TITLE
Broken/Missing Links in 16,17 Datasets

### ISSUE THREAD

**Issue by PVinay737** [ozlerhakan/mongodb-json-files#6]
Covers and YoutubeVideos Links

**Comment by MaBeuLux88** [comment]
Fixed by #7 

- Removed "/mongodb" from the covers link
- Removed the YoutubeVideos completely (404 NOT FOUND)

**Comment by ghostaccount737** [comment]
Thanks for adding the PR @MaBeuLux88 and merging it  @ozlerhakan !
